- hosts: server
  tasks:

    - name: Create ONLY my folder (safe)
      file:
        path: /usr/share/nginx/html/Midterm-2026/thy-pharoth
        state: directory
        mode: '0755'

    - name: Copy jar ONLY to my folder
      copy:
        src: target/demo-0.0.1-SNAPSHOT.jar
        dest: /usr/share/nginx/html/Midterm-2026/thy-pharoth/app.jar
        mode: '0644'