- hosts: server
  become: yes

  tasks:
    - name: Create my folder
      file:
        path: /usr/share/nginx/html/Midterm-2026/thy-pharoth
        state: directory

    - name: Copy index.html
      copy:
        src: index.html
        dest: /usr/share/nginx/html/Midterm-2026/thy-pharoth/index.html

    - name: Copy jar file
      copy:
        src: target/demo-0.0.1-SNAPSHOT.jar
        dest: /opt/thy-pharoth/app.jar