- hosts: server
  tasks:

    - name: Create nginx folder
      file:
        path: /var/www/html/Midterm-2026/thy-pharoth
        state: directory

    - name: Copy index.html
      copy:
        src: files/index.html
        dest: /var/www/html/Midterm-2026/thy-pharoth/index.html

    - name: Create app folder
      file:
        path: /opt/thy-pharoth
        state: directory

    - name: Copy jar file
      copy:
        src: target/demo-0.0.1-SNAPSHOT.jar
        dest: /opt/thy-pharoth/app.jar